### ISSUE TITLE
Aula 21/09

### ISSUE THREAD

**Issue by gloriateodoro** [paulosalvatore/Ocean_Backend_21_09_2020#1]
Boa tarde, Paulo. Eu e mais outras mulheres do Reprograma nos inscrevemos pra o curso de introdução a Backend com Node.js, porém não consegui assistir. Gostaria de saber se ela foi gravada e se está disponível em algum lugar, pois as meninas falaram muito bem e eu gostaria muito de assistir. Se não for possível, tudo bem. Obrigada!

**Comment by paulosalvatore** [comment]
Oi Glória, tudo bem?

Infelizmente os cursos do Ocean não são gravados/disponibilizados. :(

Daremos novamente o curso de backend em Outubro, iniciando em 22/10, depois em 27 e 29/10.

Também devo postar algo sobre o tema em meu canal no YouTube, de repente pode te interessar. https://www.youtube.com/channel/UCbWFEr7zsKJ92Psrfam7W8Q/

Um grande abraço!

**Comment by gloriateodoro** [comment]
Tudo bem, fico aguardando o próximo curso, então. Obrigada!
